micronaut:
  application:
    name: raidcomp-api
  server:
    cors:
      enabled: true
      configurations:
        hoppscotch:
          allowed-origins:
            - chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld
        web:
          allowed-origins:
            - https://raidcomp.uk
  http:
    services:
      wowaudit:
        url: https://wowaudit.com

datasources:
  default:
    url: jdbc:mysql://localhost/raidcomp_api?generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    dialect: MYSQL
    pooled: true
    maximum-pool-size: 10
    minimum-idle: 5
    maximum-idle: 5
    initial-size: 5
---
jpa:
  default:
    entity-scan:
      packages: 'uk.raidcomp.api.data.entity'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        hbm2ddl:
          auto: update
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

wowaudit:
  keys: ${WOWAUDIT_API_KEY}
