micronaut:
  application:
    name: raidcomp-api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost
            - http://localhost:3000
            - http://localhost:8080
            - http://lasthope.eu
            - http://lasthope.eu:3000
            - http://lasthope.eu:8080
            - http://88.99.210.51
            - http://88.99.210.51:3000
            - http://88.99.210.51:8080
          allowedHeaders:
                  - Content-Type
                  - Authorization

datasources:
  default:
    url: jdbc:mysql://localhost:3306/raidcomp_api?generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    dialect: MYSQL
    pooled: true
    maximum-pool-size: 10
    minimum-idle: 5
    maximum-idle: 5
    initial-size: 5
---
jpa:
  default:
    entity-scan:
      packages: 'uk.raidcomp.api.data.entity'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        hbm2ddl:
          auto: update
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

wowaudit:
  keys: ${WOWAUDIT_API_KEY}
