micronaut:
  application:
    name: raidcomp-api
  server:
    cors:
      enabled: true
      configurations:
        hoppscotch:
          allowed-origins:
            - chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld
        web:
          allowed-origins:
            - https://raidcomp.uk
  http:
    services:
      wowaudit:
        url: https://wowaudit.com

wowaudit:
  keys: ${WOWAUDIT_API_KEY}
